let a = [
    {
        id: 0,
        strength: 1,
        dexterity: 1,
        vitality: 1,
        intelligence: 0,
        wisdom: 0,
        charisma: 0,
    },
    {
        id: 1,
        strength: 0,
        dexterity: 1,
        vitality: 1,
        intelligence: 1,
        wisdom: 0,
        charisma: 0,
    },
    {
        id: 2,
        strength: 0,
        dexterity: 0,
        vitality: 1,
        intelligence: 1,
        wisdom: 1,
        charisma: 0,
    },
    {
        id: 3,
        strength: 0,
        dexterity: 0,
        vitality: 0,
        intelligence: 1,
        wisdom: 1,
        charisma: 1,
    },
    {
        id: 4,
        strength: 1,
        dexterity: 0,
        vitality: 1,
        intelligence: 0,
        wisdom: 1,
        charisma: 0,
    },
    {
        id: 5,
        strength: 0,
        dexterity: 1,
        vitality: 0,
        intelligence: 1,
        wisdom: 0,
        charisma: 1,
    },
    {
        id: 6,
        strength: 1,
        dexterity: 0,
        vitality: 1,
        intelligence: 0,
        wisdom: 0,
        charisma: 1,
    }];