[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet = "2.1.0"
lootitems = { path = "../loot" }
survivor = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
cc = { path = "../cc" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.7.0" }
game_entropy = { path = "../game_entropy" }
game_snapshot = { path = "../game_snapshot" }
goldenToken = { git = "https://github.com/ArichiMasaomi/golden-token" }
arcade_account = { git = "https://github.com/ArichiMasaomi/arcade-account" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
casm = true
sierra = true
