[package]
name = "game"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.0"
lootitems = { path = "../loot" }
survivor = { path = "../adventurer" }
market = { path = "../market" }
obstacles = { path = "../obstacles" }
cc = { path = "../cc" }
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts", ref = "v0.8.0-beta.1" }

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
allowed-libfuncs = true
